import 'dotenv/config'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/context/index.provider";
import Link from "next/link";
import { BarChart2, Upload, Users, Video } from "lucide-react";
import { currentUser } from "@/data/mockData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bienvenue dans fi.ly",
  description: "Generated by create next app",
};

const HomeLayout = ({children}: {children: React.ReactNode}) => {
  return (
      
    <div className="min-h-screen bg-gray-50">
      <nav className="bg-white border-b border-gray-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16">
            <div className="flex">
              <Link href="/" className="flex items-center">
                <Video className="h-8 w-8 text-blue-600" />
                <span className="ml-2 text-xl font-bold text-gray-900">file.ly</span>
              </Link>
            </div>
            <div className="flex items-center">
              <img
                className="h-8 w-8 rounded-full"
                src={currentUser.avatar}
                alt={currentUser.name}
              />
            </div>
          </div>
        </div>
      </nav>

      <div className="flex">
        <aside className="w-64 bg-white border-r border-gray-200 min-h-screen">
          <nav className="mt-5 px-2">
            <Link
              href="/videos/mine"
              className="group flex items-center px-2 py-2 text-sm font-medium rounded-md text-gray-900 hover:bg-gray-50"
            >
              <Video className="mr-3 h-5 w-5 text-gray-500" />
              Mes videos
            </Link>
            <Link
              href="/analytics"
              className="mt-1 group flex items-center px-2 py-2 text-sm font-medium rounded-md text-gray-900 hover:bg-gray-50"
            >
              <BarChart2 className="mr-3 h-5 w-5 text-gray-500" />
              Tableau de bord
            </Link>
            <Link
            
              href="/shared"
              className="mt-1 group flex items-center px-2 py-2 text-sm font-medium rounded-md text-gray-900 hover:bg-gray-50"
            >
              <Users className="mr-3 h-5 w-5 text-gray-500" />
              Partages en cours
            </Link>
            <button
              className="mt-1 group flex items-center px-2 py-2 text-sm font-medium rounded-md text-gray-900 hover:bg-gray-50 w-full"
            >
              <Upload className="mr-3 h-5 w-5 text-gray-500" />
              Nouvelle video
            </button>
          </nav>
          <div className="flex-shrink-0 flex border-t border-gray-200 p-4">
            <button className="flex-shrink-0 w-full group block">
              <div className="flex items-center">
                <div>
                  <img
                    className="inline-block h-9 w-9 rounded-full"
                    src={currentUser.avatar}
                    alt=""
                  />
                </div>
                <div className="ml-3">
                  <p className="text-sm font-medium text-gray-700 group-hover:text-gray-900">
                    {currentUser.name}
                  </p>
                  <p className="text-xs font-medium text-gray-500 group-hover:text-gray-700">
                    Mon profile
                  </p>
                </div>
              </div>
            </button>
          </div>
        </aside>

        <main className="flex-1 p-6">
          {children}
        </main>
      </div>
    </div>
);
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <HomeLayout>
            {children}
          </HomeLayout>
        </Providers>
      </body>
    </html>
  );
}
