import 'dotenv/config'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/context/index.provider";
import Link from "next/link";
import { BarChart2, Upload, Users, Video } from "lucide-react";
import { currentUser } from "@/data/mockData";
import { AppSidebar } from '@/components/app-sidebar';
import { SidebarProvider } from '@/components/ui/sidebar';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { HeaderSummarizeDashboard } from '@/components/dashboard/header-summarize-dashboard';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bienvenue dans fi.ly",
  description: "Generated by create next app",
};

const HomeLayout = ({children}: {children: React.ReactNode}) => {
  return (
      
      <SidebarProvider>
        <AppSidebar />
        <div className='flex-1 flex bg-blue-100 flex-col'>
          <HeaderSummarizeDashboard />
          {children}
        </div>
      </SidebarProvider>
);
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <HomeLayout>
            {children}
          </HomeLayout>
        </Providers>
      </body>
    </html>
  );
}
